language: go
go:
  - 1.2

branches:
  only:
    - master

install:
  - DST=~/gopath/src/github.com/apcera
  - mkdir -p "$DST"
  - git clone --depth=1 --quiet https://github.com/apcera/nats.git "$DST"/nats
  - go get code.google.com/p/go.tools/cmd/vet

script:
  - go build
  - go fmt ./...
  - go vet ./...
  - go test -i -race ./...
  - go test -v -race ./...
