
os: linux
dist: focal

vm:
  size: 2x-large

language: go
go:
- 1.17.x
- 1.16.x

addons:
  apt:
    packages:
    - rpm
go_import_path: github.com/nats-io/nats-server

env:
- TEST_SUITE=compile
- TEST_SUITE=no_race_tests
- TEST_SUITE=js_tests
- TEST_SUITE=js_cluster_tests
- TEST_SUITE=srv_pkg_non_js_tests
- TEST_SUITE=non_srv_pkg_tests

script: ./runTestsOnTravis.sh $TEST_SUITE

deploy:
  provider: script
  cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    condition: ($TRAVIS_GO_VERSION =~ 1.17) && ($TEST_SUITE = "compile")
