language: go
go:
- 1.6
install:
- go get github.com/nats-io/nats
- go get github.com/mattn/goveralls
- go get github.com/wadey/gocovmerge
script:
- go build
- go fmt ./...
- go vet ./...
- go test -i -race ./...
- go test -v -race ./...
- ./scripts/cov.sh TRAVIS
